#!/bin/sh
# launch Diagram Editor

# resolve symlinks
me="$0"
resolved=`readlink "$me"`
while [ $? -eq 0 -a x"$me" != x"$resolved" ]; do
  me="$resolved"
  resolved=`readlink "$me"`
done

instdir=`dirname "$me"`

# Use the JAR file if is there.
jarfile="$instdir/dist/ded.jar"
if [ -f "$jarfile" ]; then
  exec java -ea -jar "$jarfile" "$@"
fi

classpath="$instdir/bin"
if [ -d "$classpath" ]; then
  exec java -classpath "$classpath" -ea ded.Ded "$@"
else
  echo "Missing: $classpath or $jarfile"
  echo "Maybe the sources are not compiled?  Try running 'make'."
fi

# EOF
